"""
AI Daily Coding Tips Generator
--------------------------------
Generates educational markdown coding tips.

Safe & educational automation:
- No spam behavior
- No fake engagement
- Useful learning-focused content
"""

import os
import random
from datetime import datetime

# Educational tip database
TIPS = {
    "Python": [
        {
            "title": "Use List Comprehensions",
            "content": (
                "List comprehensions provide a concise way to create lists.\n\n"
                "```python\n"
                "squares = [x * x for x in range(10)]\n"
                "```\n\n"
                "They improve readability and reduce boilerplate loops."
            ),
        },
        {
            "title": "Use enumerate() Instead of Manual Counters",
            "content": (
                "```python\n"
                "for index, value in enumerate(items):\n"
                "    print(index, value)\n"
                "```\n\n"
                "Cleaner and more Pythonic than manually incrementing counters."
            ),
        },
    ],
    "Git": [
        {
            "title": "Write Meaningful Commit Messages",
            "content": (
                "Good commit messages improve collaboration.\n\n"
                "Example:\n\n"
                "```bash\n"
                "git commit -m \"Fix login validation bug\"\n"
                "```\n"
            ),
        },
        {
            "title": "Use git stash Before Experimenting",
            "content": (
                "```bash\n"
                "git stash\n"
                "```\n\n"
                "Temporarily save unfinished work without committing."
            ),
        },
    ],
    "Docker": [
        {
            "title": "Use Small Base Images",
            "content": (
                "Smaller Docker images improve build speed and security.\n\n"
                "Example:\n\n"
                "```dockerfile\n"
                "FROM python:3.12-slim\n"
                "```\n"
            ),
        }
    ],
    "APIs": [
        {
            "title": "Always Handle API Errors",
            "content": (
                "Never assume APIs always return success.\n\n"
                "```python\n"
                "response.raise_for_status()\n"
                "```\n"
            ),
        }
    ],
    "JavaScript": [
        {
            "title": "Prefer const by Default",
            "content": (
                "Use `const` unless reassignment is required.\n\n"
                "```javascript\n"
                "const apiUrl = 'https://example.com';\n"
                "```\n"
            ),
        }
    ],
    "AI": [
        {
            "title": "Prompt Engineering Matters",
            "content": (
                "Clear prompts improve AI responses.\n\n"
                "Good prompts include:\n"
                "- Context\n"
                "- Constraints\n"
                "- Desired output format\n"
            ),
        }
    ],
    "System Design": [
        {
            "title": "Caching Improves Performance",
            "content": (
                "Caching reduces repeated computations and database load.\n\n"
                "Popular caching tools:\n"
                "- Redis\n"
                "- Memcached\n"
            ),
        }
    ],
}


def create_tip():
    """Generate a markdown coding tip."""

    category = random.choice(list(TIPS.keys()))
    tip = random.choice(TIPS[category])

    now = datetime.now()

    date_folder = now.strftime("%Y-%m-%d")
    timestamp = now.strftime("%H-%M-%S")

    directory = os.path.join("tips", date_folder)
    os.makedirs(directory, exist_ok=True)

    filename = f"tip-{timestamp}.md"
    filepath = os.path.join(directory, filename)

    markdown = f"""# 💡 {tip['title']}

**Category:** {category}  
**Generated:** {now.strftime("%Y-%m-%d %H:%M:%S")}

---

{tip['content']}

---

## 📘 Why This Matters

Consistent learning and small improvements compound over time.
Understanding these concepts helps build stronger engineering habits.

---

### 🤖 Automation Notice

This educational tip was automatically generated by the
AI Daily Coding Tips project using Python automation.
"""

    with open(filepath, "w", encoding="utf-8") as file:
        file.write(markdown)

    print(f"Generated: {filepath}")
    return filepath


if __name__ == "__main__":
    create_tip()