name: AI Daily Coding Tips

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-tip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scheduler
        id: scheduler
        run: |
          python scripts/scheduler.py

      - name: Generate Coding Tip
        if: success()
        run: |
          python scripts/generate.py

      - name: Commit Changes
        run: |
          git config --global user.name "shriram7057"
          git config --global user.email "shriram7057@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes detected."
            exit 0
          fi

          COMMIT_MESSAGE="docs: publish daily coding tip"

          git commit -m "$COMMIT_MESSAGE"
          git pull --rebase
          git push
